# Generated by Django 6.0.3 on 2026-04-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='CategoriaProd',
        ),
        migrations.AlterModelOptions(
            name='categoriaprod',
            options={'verbose_name': 'categoria producto', 'verbose_name_plural': 'categorias productos'},
        ),
    ]
